<?php /** @var Stuntcoders_Banner_Block_Banner $this */ ?>
<div class="banner-wrapper">
    <a href="<?php echo $this->getUrl(); ?>" <?php echo $this->getOpenInNewTab() ?  'target="_blank"' : ''; ?>>
        <div class="banner">
            <img src="<?php echo $this->getImage(); ?>" alt="<?php echo $this->getHeading(); ?>">
            <p class="banenr-title"><?php echo $this->getHeading(); ?></p>
            <p class="banner-content"><?php echo $this->getText(); ?></p>
        </div>
    </a>
</div>
