<?php /** @var Stuntcoders_Banner_Block_Banner_Group $this */ ?>
<div class="banner-group-wrapper">
    <?php foreach ($this->getGroup()->getBannerCollection() as $banner): ?>
        <?php /** @var Stuntcoders_Banner_Model_Banner $banner */ ?>
        <div class="banner-wrapper">
            <a href="<?php echo $this->getUrl(); ?>" <?php echo $banner->getOpenInNewTab() ?  'target="_blank"' : ''; ?>>
                <div class="banner">
                    <img src="<?php echo $banner->getImage(); ?>" alt="<?php echo $banner->getTitle(); ?>">
                    <p class="banenr-title"><?php echo $banner->getTitle(); ?></p>
                    <p class="banner-content"><?php echo $banner->getContent(); ?></p>
                </div>
            </a>
        </div>
    <?php endforeach; ?>
</div>
