<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="width:50%;"><h3 class="icon-head head-blog"><?php echo Mage::helper('adminhtml')->__('Banner Manager') ?></h3></td>
            <td class="a-right">
                <?php echo $this->getAddNewButtonHtml() ?>
            </td>
        </tr>
    </table>
</div>
<div>
    <?php echo $this->getFormHtml() ?>
</div>
<?php if (Mage::registry('stuntcoders_banner_group_data')): ?>
    <div class="content-header">
        <table cellspacing="0">
            <tr>
                <td style="width:50%;"><h3 class="icon-head head-blog"><?php echo Mage::helper('adminhtml')->__('Banners') ?></h3></td>
            </tr>
        </table>
    </div>
    <div>
        <?php echo $this->getBannersHtml()?>
    </div>
<?php endif; ?>
<script type="text/javascript">
    var banner_form = new varienForm('banner_group_form');

    (function registerEvents(grid) {
        for (var i = 2; i < grid.rows.length; i++) {
            Event.observe(grid.rows[i].select('.input-text')[0], 'keyup', updateGridInput);
        }
    }) ($('bannerGrid_table'));

    function updateGridInput() {
        var data = {};
        var grid = $('bannerGrid_table');
        for (var i = 2; i < grid.rows.length; i++) {
            data[parseInt(grid.rows[i].cells[0].innerHTML)] = parseInt(grid.rows[i].select('.input-text')[0].value);
        }

        $('banner_positions').value = JSON.stringify(data);
    }
    //</script>
